# Generated by Django 4.1.7 on 2023-02-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='contents',
            field=models.ManyToManyField(blank=True, to='content.content'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='subchannels',
            field=models.ManyToManyField(blank=True, to='channel.channel'),
        ),
    ]
