# Generated by Django 4.1.7 on 2023-02-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('rating', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('source', models.CharField(max_length=512)),
                ('metadata', models.JSONField(null=True)),
            ],
        ),
    ]
